-- R-XX (a pedido explícito, fuera del plan post-directiva): resúmenes
-- extensos y ESTÁTICOS de los módulos 1 a 5, para la sección «Mi módulo» del
-- perfil del estudiante. Se generaron a partir de las presentaciones reales
-- de cada profesor (docs/Presentaciones para resumen de los modulos/).
--
-- Actualiza por order_index, no por program_id: PTMA y PFTA comparten el
-- mismo currículo de 14 módulos con nombres y orden idénticos (confirmado
-- por consulta), así que un solo UPDATE cubre ambos programas a la vez.
--
-- Son estáticos a propósito: no cambian automáticamente si se crea un
-- nuevo programa ni con el paso del tiempo. Solo se editan a mano, desde la
-- pantalla de administración (solo super_admin y dirección académica,
-- migración 066 ya deja escribir 'modules' únicamente a is_academico()).


update public.modules set description = 'En este módulo arrancas por lo más básico: qué es la mecánica automotriz y por qué el carro se entiende mejor como un sistema, no como piezas sueltas. Vas a ver cómo conversan entre sí la transmisión, la dirección, la suspensión, los frenos, el sistema eléctrico, la refrigeración, la lubricación, el escape y el aire acondicionado — cada uno con su función, pero todos dependiendo unos de otros para que el carro se mueva, frene y sea seguro.

Entras después al corazón del vehículo: el motor de combustión interna. Vas a aprender sus piezas principales — bloque, pistones, cigüeñal, cárter y culata — y a entender el ciclo de cuatro tiempos (admisión, compresión, combustión y escape) paso por paso, así como las formas de clasificar un motor: por combustible, por disposición de cilindros, por cantidad de cilindros y por tipo de ciclo.

Una parte grande del módulo es mantenimiento: cada cuántos kilómetros toca cambiar aceite, rotar cauchos, revisar líquidos; la diferencia entre mantenimiento correctivo, preventivo, predictivo y proactivo; y un cronograma básico (mensual, trimestral, semestral, anual) que vas a usar en el taller. También entra la conducción técnica — anticipación, distancia de seguridad, manejo de revoluciones — porque un buen técnico también sabe cómo se cuida un carro desde el volante.

Luego viene diagnóstico preliminar: cómo reconocer las fallas más comunes por sus síntomas — dificultad de arranque, sobrecalentamiento, pérdida de potencia, vibraciones — y qué dice cada testigo del tablero (check engine, presión de aceite, batería, temperatura, ABS). Vas a conocer las herramientas básicas de diagnóstico (escáner OBD-II, multímetro, punta lógica) y los dos tipos de inspección visual, directa y remota (boroscopios, videoendoscopios).

El módulo cierra con dos temas que son la base de cualquier carrera en un taller: seguridad industrial (los riesgos reales de un taller, los equipos de protección personal por zona del cuerpo, y las normas para elevar un vehículo sin que nadie salga lastimado) y cómo funciona un taller profesional de principio a fin — recepción, diagnóstico, presupuesto, reparación, entrega, gestión de repuestos, garantías, y por qué la negligencia mecánica tiene consecuencias legales y no solo técnicas.' where order_index = 1;
update public.modules set description = 'Este módulo es el de instrumentación: aprender a medir con precisión antes de tocar nada. Empiezas por metrología — qué es, de dónde viene la necesidad de estandarizar medidas, y los conceptos básicos que vas a usar todo el curso: instrumento de medición, unidad de medida, rango, precisión y error. De ahí pasas a manejar los dos sistemas de unidades que te vas a encontrar en cualquier taller — el métrico (MKS) y el inglés (pulgadas, pies, libras) — y cómo convertir entre ellos sin perderte.

La parte central del módulo son los instrumentos de medición de taller. Vas a aprender a usar el vernier o pie de rey, y en profundidad el micrómetro: sus partes (cuerpo, husillo, tope, tambor fijo, tambor móvil, trinquete), los distintos tipos (exteriores, interiores, profundidades, roscas, digitales) y cómo leer una medida en milímetros paso a paso. También entra el torquímetro — qué es el torque, cómo se calcula (fuerza por brazo) y los tipos que vas a encontrar (de click, de aguja, de carátula, angular) — el multímetro (voltaje, corriente, resistencia, continuidad, y cómo probar tomas de corriente, baterías e interruptores) y el manómetro de presión, con sus usos específicos en neumáticos, suspensión neumática, aceite, frenos y aire acondicionado. Se incluye también una guía visual de tornillería: medidas, tablas de conversión y equivalencias que vas a necesitar todo el tiempo en el taller.

La segunda mitad del módulo es sobre las herramientas de taller: uso, aplicación y conservación. No es solo saber qué es cada herramienta, sino aprender la razón técnica detrás de usarla bien — la prensa de banco, los burros o caballetes, los gatos hidráulicos, las calzas de seguridad, martillos según su cabeza, botadores para transmisiones sincrónicas, alicates según su tipo, pinzas saca-retenes, extractores de poleas y rodamientos, destornilladores, llaves fijas y de corona, dados y ratchets, la llave de cruz, el torquímetro como herramienta de control de calidad, el calibrador de aire, la pistola de impacto neumática y el compresor de aire. De cada una vas a ver para qué sirve, por qué importa usarla correctamente (y qué se rompe si no), buenas prácticas de uso y cómo se mantiene. El módulo cierra con los hábitos de conservación de herramientas: limpieza después de cada jornada, lubricación de partes móviles, almacenamiento correcto e inspección visual de seguridad antes y después de cada uso — porque el estado de las herramientas de un técnico dice quién es.' where order_index = 2;
update public.modules set description = 'Este módulo es sobre los fluidos que mantienen vivo a un vehículo, empezando por la tribología (el estudio de la fricción, el desgaste y la lubricación) y los lubricantes: qué son, para qué sirven (reducir desgaste y fricción, evitar corrosión, controlar contaminación y calor, transmitir potencia, sellar) y en qué formas vienen (líquidos, semisólidos, sólidos, spray). Vas a entender qué es un lubricante terminado — aceite básico más un paquete de aditivos — y los tipos de aceites básicos: minerales, sintéticos, re-refinados y de grado alimenticio, además de la clasificación API que separa a los básicos en grupos según su composición.

Le sigue un bloque completo sobre aditivos: protectores de la superficie (antidesgaste, extrema presión, inhibidores de corrosión, detergentes, dispersantes, modificadores de fricción), protectores del lubricante (antiespumantes, antioxidantes) y mejoradores del funcionamiento (depresores del punto de fluidez, mejoradores del índice de viscosidad, emulsificantes y demulsificantes). Vas a aprender qué es la viscosidad, cómo se mide, qué significa que un aceite sea multigrado (por ejemplo 15W-40) y qué es el índice de viscosidad. También vas a conocer las clasificaciones SAE/ISO por viscosidad y las clasificaciones API para motores a gasolina y a diésel, y a desmontar los mitos más comunes de lubricación — por ejemplo que "mientras más viscoso, mejor", o que un aceite oscuro es señal de que está malo.

Después entras a los fluidos automotrices más allá del aceite de motor: líquido de frenos (qué es, cómo funciona en frenos de disco y de tambor, y la norma Covenin que lo regula), líquido refrigerante (su composición, para qué sirve y cada cuánto se cambia), y una revisión de productos especializados de taller — agua para baterías, mejorador de octanaje, líquido limpiaparabrisas, abrillantadores, shampoo, desengrasantes y grasa multiuso. Sobre la grasa lubricante vas a ver su composición, ventajas y desventajas frente al aceite, cómo se almacena correctamente y la fórmula para calcular cuánta grasa necesita un rodamiento. También se cubren los filtros de aceite: qué contaminantes detienen y los criterios técnicos para elegir el filtro correcto.

El módulo cierra con transmisiones de potencia — automáticas, manuales, todoterreno e industriales — viendo los fluidos específicos que necesita cada una (ATF, aceites para CVT, para diferenciales) y por qué usar el fluido equivocado en una caja automática puede arruinarla. Y termina con el modelo de la "curva de la bañera" para entender cómo fallan los componentes con el tiempo (fallas iniciales de fabricación, vida útil, desgaste) y qué significa ser un técnico automotriz excelente: aprender el lenguaje de la lubricación, certificarse, practicar el mantenimiento proactivo y anticiparse a las fallas en vez de solo repararlas.' where order_index = 3;
update public.modules set description = 'Este módulo profundiza en el motor de combustión interna, el corazón del vehículo. Empiezas por entender qué es un motor en general — una máquina que transforma energía en trabajo — y la diferencia entre un motor térmico (que convierte calor en movimiento) y un motor eléctrico (que convierte electricidad en movimiento por campos magnéticos). De ahí vas a la clasificación completa de los motores térmicos: de combustión externa (como las máquinas y turbinas de vapor) y de combustión interna, tanto alternativos (motores de explosión a gasolina y de combustión a gasoil) como rotativos (turbinas de gas, motor Wankel). También vas a ver cómo se clasifican específicamente los motores de gasolina según su sistema de encendido (platinos o electrónico) y de alimentación de combustible (carburación, inyección monopunto, multipunto o de control electrónico).

La parte central es un repaso a fondo de cada componente del motor de combustión interna: el bloque motor (qué determina la cilindrada, los tipos de camisa de cilindro seca y húmeda, y las disposiciones en línea, en V y bóxer), los pistones y sus tipos según cabeza, faldón y combustible, las bielas (que conectan el pistón con el cigüeñal), el cigüeñal (monolítico o ensamblado), el cárter (donde vive el aceite del motor) y la culata (donde están las válvulas, los muelles y la cámara de combustión).

El módulo cierra explicando en detalle el funcionamiento del motor de cuatro tiempos, tiempo por tiempo: admisión (el pistón baja, la válvula de admisión se abre y entra la mezcla aire-combustible), compresión (las válvulas se cierran, el pistón sube y comprime la mezcla), combustión o explosión (la chispa de la bujía enciende la mezcla y el pistón es empujado hacia abajo con fuerza) y escape (la válvula de escape se abre y el pistón expulsa los gases quemados). Vas a entender por qué este ciclo se repite continuamente en cada cilindro y cómo ese movimiento lineal del pistón se convierte, a través de la biela y el cigüeñal, en el movimiento giratorio que finalmente mueve el vehículo.' where order_index = 4;
update public.modules set description = 'Este módulo entra en los sistemas de transmisión: cómo se traslada la potencia del motor hasta las ruedas, y por qué eso casi nunca es un camino directo. Empiezas por entender qué es un sistema mecánico en general — motor (el que aporta la energía), carga (lo que la recibe y usa), transmisión (el elemento intermedio que comunica esa energía y puede alterar velocidad y fuerza) y dispositivos auxiliares (volantes de inercia, frenos, reguladores).

De ahí vas a los principios físicos que explican por qué funciona una transmisión, presentados siempre con su aplicación práctica en el taller: qué es una fuerza y qué es el momento (o torque) de una fuerza — la idea de que la misma fuerza aplicada más lejos del punto de giro produce más "efecto de rotación"; qué es el trabajo mecánico y la potencia (la rapidez con la que se hace ese trabajo), y por qué en los motores hablamos de HP en vez de kW y de RPM en vez de rad/s. También vas a entender, de forma conceptual, qué es la inercia y por qué a un objeto le cuesta más o menos girar según cómo esté repartida su masa — es la razón por la que el volante de inercia existe.

Entras después al tema central: la relación de transmisión y la multiplicación de torque. Un motor no entrega la misma fuerza a cualquier velocidad — tiene una curva característica, con un mínimo de revoluciones (el ralentí) por debajo del cual se apaga, y un punto óptimo de torque. Cuando esa fuerza del motor no alcanza para mover la carga, la transmisión actúa como un amplificador: intercambia velocidad por fuerza (nunca puede aumentar ambas a la vez), y ese intercambio se mide con dos números clave — la relación de transmisión y la eficiencia mecánica (ninguna transmisión real es 100% eficiente; normalmente rondan 95-98%).

Vas a ver los dos tipos básicos de transmisión mecánica — por engranajes (donde la forma del diente, llamada evolvente, permite que engranen sin interferencia) y por correa — y cómo funciona por dentro una caja manual sincronizada: por qué los engranajes no se conectan directamente entre sí (chocarían y se destruirían si giran a distinta velocidad), sino que permanecen siempre engranados entre ejes, y es un collar deslizante con anillo sincronizador el que iguala las velocidades antes de trabar el conjunto — el mismo principio, sea en un carro o en una moto ("synchromesh").

Después entra el sistema de embrague: qué es (un interruptor mecánico que conecta o desconecta dos elementos, normalmente en contacto), los tipos que vas a encontrar — de disco simple, doble disco, multidisco (típico en cajas automáticas y motos), centrífugo, dual (DCT) y unidireccional — y qué factores hacen que un embrague transmita más torque: más fuerza de apriete, mayor radio, mejor coeficiente de fricción entre los materiales, o más pares de superficies en contacto (por eso existen los embragues multidisco).

El módulo cierra con las transmisiones automáticas: cómo funciona el acoplamiento hidráulico (una bomba y una turbina que se comunican por fluido, sin contacto mecánico directo), por qué eso genera deslizamiento e ineficiencia — y cómo se resuelve con un embrague de bloqueo y un convertidor de par — y cómo funcionan por dentro los trenes epicíclicos o planetarios que reemplazan a los engranajes y sincronizadores de una caja manual, controlados por embragues hidráulicos que una computadora activa según la velocidad del vehículo y del motor, todo dentro del cuerpo de válvulas.' where order_index = 5;
